export const SEND_MESSAGE = "SEND_MESSAGE";
export const APPEND_MESSAGE = "APPEND_MESSAGE";
export const APPEND_MESSAGES = "APPEND_MESSAGES";
export const CREATE_REQUEST = "CREATE_REQUEST";
export const APPEND_REQUEST = "APPEND_REQUEST";

export const FETCH_ALL_REQUESTS = "FETCH_ALL_REQUESTS";
export const APPEND_REQUESTS = "APPEND_REQUESTS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
