export const SEND_MESSAGE = "SEND_MESSAGE";
export const APPEND_MESSAGE = "APPEND_MESSAGE";
export const APPEND_MESSAGES = "APPEND_MESSAGES";
export const CREATE_REQUEST = "CREATE_REQUEST";
export const APPEND_REQUEST = "APPEND_REQUEST";

export const APPEND_CHANNEL = "APPEND_CHANNEL";
export const APPEND_CHANNELS = "APPEND_CHANNELS";
export const UPDATE_CHANNEL = "UPDATE_CHANNEL";

export const UPDATE_STOCKS = "UPDATE_STOCKS";

export const FETCH_ALL_REQUESTS = "FETCH_ALL_REQUESTS";
export const APPEND_REQUESTS = "APPEND_REQUESTS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const APPEND_STOCK_SERIES = "APPEND_STOCK_SERIES";
